name: armpet_wash_mobile
description: "A Elite car wash Project."

publish_to: 'none'

version: 1.0.317

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  device_info_plus: ^11.4.0
  uuid: ^4.5.1
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 2.4.8
  hive_generator: 2.0.0
  json_serializable: ^6.8.0
  freezed: ^2.4.4



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app.png"
  min_sdk_android: 21
